version: '3.8'

services:

  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql
    ports:
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=A&VeryComplex123Password

  api:
    image: securenotes.api
    build:
      context: .
      dockerfile: SecureNotes.API/Dockerfile
    depends_on:
      - sql
    ports:
      - "5000:80"
   
  blazor:
    image: securenotes.blazor
    build:
      context: .
      dockerfile: SecureNotes.Blazor/Dockerfile
    ports:
      - "8080:80"

